# 2.5.4 El truco log-sum-exp

**Función log-sum-exp (lse):** $\;$ cálculo robusto del logaritmo de la suma de logits $\boldsymbol{a}\in\mathbb{R}^C$
$$\operatorname{lse}(\boldsymbol{a})%
=\log\sum_{c=1}^C \exp(a_c)%
=\max_{c'} a_{c'}+\log\sum_{c=1}^C \exp(a_c-\max_{c'} a_{c'})$$

In [1]:
import warnings; warnings.filterwarnings("ignore"); import numpy as np; from scipy.special import logsumexp
a1 = np.array([0, 1, 0]);            print(np.log(np.sum(np.exp(a1))), logsumexp(a1))
a2 = np.array([1000, 1001, 1000]);   print(np.log(np.sum(np.exp(a2))), logsumexp(a2))
a3 = np.array([-1000, -999, -1000]); print(np.log(np.sum(np.exp(a3))), logsumexp(a3))

1.5514447139320509 1.551444713932051
inf 1001.551444713932
-inf -998.448555286068


**Cáculo robusto de posteriors categóricos:**
$$p(y=c\mid\boldsymbol{x})%
=\frac{\exp(a_c)}{\sum_{c'=1}^C \exp(a_{c'})}%
=\exp\left(\log(\exp(a_c))-\log\sum_{c'=1}^C \exp(a_{c'})\right)%
=\exp(a_c-\operatorname{lse}(\boldsymbol{a}))$$

In [2]:
print(np.exp(a1-logsumexp(a1))); print(np.exp(a2-logsumexp(a2))); print(np.exp(a3-logsumexp(a3)))

[0.21194156 0.57611688 0.21194156]
[0.21194156 0.57611688 0.21194156]
[0.21194156 0.57611688 0.21194156]
