# 7.5.2 Conexión entre la SVD y la EVD

## Matriz cuadrada real, simétrica y definida positiva

Sea $\mathbf{A}\in\mathbb{R}^{n\times n}$ real, simétrica y definida positiva, con EVD $\,\mathbf{A}=\mathbf{E}\mathbf{\Lambda}\mathbf{E}^t\,$ y $\,$ SVD $\,\mathbf{A}=\mathbf{U}\mathbf{S}\mathbf{V}^t$.

**Valores singulares igual a propios:** $\;\mathbf{S}=\mathbf{\Lambda}$

**Vectores singulares izquierdos y derechos igual a propios (salvo cambios de signo):** $\;\mathbf{U}=\mathbf{V}=\mathbf{E}$

In [1]:
import numpy as np
X = np.array([ [-1, -1], [0, 2], [2, 0], [3, 3] ]).astype(float)
A = np.cov(X.T, bias=True)
L, E = np.linalg.eigh(A)
i = L.argsort()[::-1]; L = L[i]; E = E[:,i]
print("EVD:\n", L, "\n", E, "\n")
U, S, Vt = np.linalg.svd(A) # np devuelve valores singulares en orden no creciente
print("SVD:\n", U, "\n", S, "\n", Vt)

EVD:
 [4. 1.] 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]] 

SVD:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]] 
 [4. 1.] 
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


## Matriz real arbitraria

Sea $\mathbf{A}\in\mathbb{R}^{m\times n}$ real con SVD $\;\mathbf{A}=\mathbf{U}\mathbf{S}\mathbf{V}^t$.

**Vectores y valores propios de $\mathbf{A}^t\mathbf{A}$:** $\;\mathbf{V}\;$ y $\;\mathbf{D}_n=\mathbf{S}^t\mathbf{S}$
$$\mathbf{A}^t\mathbf{A}=\mathbf{V}\mathbf{S}^t\mathbf{U}^t\mathbf{U}\mathbf{S}\mathbf{V}^t=\mathbf{V}(\mathbf{S}^t\mathbf{S})\mathbf{V}^t\;\Rightarrow\;(\mathbf{A}^t\mathbf{A})\mathbf{V}=\mathbf{V}\mathbf{D}_n$$

**Vectores y valores propios de $\mathbf{A}\mathbf{A}^t$:** $\;\mathbf{U}\;$ y $\;\mathbf{D}_m=\mathbf{S}\mathbf{S}^t$
$$\mathbf{A}\mathbf{A}^t=\mathbf{U}\mathbf{S}\mathbf{V}^t\mathbf{V}\mathbf{S}^t\mathbf{U}^t=\mathbf{U}(\mathbf{S}\mathbf{S}^t)\mathbf{U}^t\;\Rightarrow\;(\mathbf{A}\mathbf{A}^t)\mathbf{U}=\mathbf{U}\mathbf{D}_m$$

**Thin SVD:** $\;\mathbf{S}\in\mathbb{R}^{r\times r}\;$ con $r=\min(m, n),\;$ por lo que $\;\mathbf{D}=\mathbf{S}^2=\mathbf{S}^t\mathbf{S}=\mathbf{S}\mathbf{S}^t$

**Existencia de la SVD:** $\;$ la EVD no siempre existe (incluso con $\mathbf{A}$ cuadrada); $\;$ la SVD sí