# 7.5.5 SVD truncada

## SVD truncada

**SVD $K$-truncada:** $\;\mathbf{\hat{A}}_K=\mathbf{U}_K\mathbf{S}_K\mathbf{V}_K^t,\,$ aproximación de rango $K$ de $\mathbf{A}\in\mathbb{R}^{m\times n}$ construida a partir de sus $K$ mayores valores singulares, junto con sus $K$ vectores singulares asociados, izquierdos y derechos

**Optimalidad de la SVD $K$-truncada:** $\;\mathbf{\hat{A}}_K\,$ es la mejor aproximación de $\mathbf{A}$ en norma Frobenius (al cuadrado), $\,\lVert\mathbf{A}-\mathbf{\hat{A}}_K\rVert_F^2$

## PCA con la SVD

Sea $\mathbf{X}\in\mathbb{R}^{N\times D}$ una matriz de datos **centrada** de matriz de covarianzas empírica $\mathbf{\Sigma}=\frac{1}{N}\mathbf{X}^t\mathbf{X}\,$ (simétrica y semi-definida positiva) 

**SVD $K$-truncada de $\mathbf{X}$:** $\quad\mathbf{\hat{X}}_K=\mathbf{U}_K\mathbf{S}_K\mathbf{V}_K^t$

**SVD $K$-truncada de $\mathbf{\Sigma}$:** $\quad\mathbf{\hat{\Sigma}}_K=\mathbf{E}_K\boldsymbol{\Lambda}_K\mathbf{E}_K^t\;$ con $\;\mathbf{E}_K=\mathbf{V}_K\;$ y $\;\boldsymbol{\Lambda}_K=\frac{1}{N}\mathbf{S}_K^2$

**PCA de $\mathbf{X}$ con la SVD:** $\quad\operatorname{PCA}(\mathbf{X})=\mathbf{X}\mathbf{E}_K\approx\mathbf{U}_K\mathbf{S}_K\mathbf{V}_K^t\mathbf{V}_K=\mathbf{U}_K\mathbf{S}_K\quad$ no requiere $\mathbf{\Sigma}$

**Reconstrucción de $\mathbf{X}$ tras PCA:**  $\quad\mathbf{\hat{X}}_K=\operatorname{PCA}(\mathbf{X})\mathbf{V}_K^t$


In [1]:
import numpy as np
X = np.array([ [-1, -1], [0, 2], [2, 0], [3, 3] ]).astype(float)
X = X - np.mean(X, axis=0)
U, S, Vt = np.linalg.svd(X)
Xr = U[:, 0] * S[0]
print("Datos centrados:\n", X, "\nComponente principal 1:\n", Vt[:, 0], "\nDatos reducidos:\n", Xr)
print("Datos reconstruidos:\n", Xr.reshape(-1, 1) @ Vt[0, :].reshape(1, -1))

Datos centrados:
 [[-2. -2.]
 [-1.  1.]
 [ 1. -1.]
 [ 2.  2.]] 
Componente principal 1:
 [0.70710678 0.70710678] 
Datos reducidos:
 [-2.82842712e+00  4.31373875e-16 -3.41684101e-17  2.82842712e+00]
Datos reconstruidos:
 [[-2.00000000e+00 -2.00000000e+00]
 [ 3.05027392e-16  3.05027392e-16]
 [-2.41607145e-17 -2.41607145e-17]
 [ 2.00000000e+00  2.00000000e+00]]
