# 13.3.3.4 Todo junto

## Gradiente de la pérdida respecto a los logits $\boldsymbol{a}$
$$\boldsymbol{u}_2=\boldsymbol{\nabla}_{\boldsymbol{a}}\mathcal{L}%
=\biggl(\frac{\partial\mathcal{L}}{\partial\boldsymbol{a}}\biggr)^t%
=(\boldsymbol{p}-\boldsymbol{y})^t\in\mathbb{R}^{1\times C}$$

In [6]:
u2 = y_pred - y
print('u2 =', str(u2).replace('\n',''))

u2 = tf.Tensor([[-0.2689  0.2689] [ 0.2689 -0.2689] [ 0.2689 -0.2689] [-0.7311  0.7311]], shape=(4, 2), dtype=float32)


### Respecto a la linealidad de la capa de salida $\mathbf{V}$
$$\boldsymbol{\nabla}_{\mathbf{V}}\mathcal{L}%
=\biggl[\frac{\partial\mathcal{L}}{\partial\mathbf{V}}\biggr]_{1,:}%
=\biggl[\frac{\partial\mathcal{L}}{\partial\boldsymbol{a}}\frac{\partial\boldsymbol{a}}{\partial\mathbf{V}}\biggr]_{1,:}%
=\biggl[\boldsymbol{u}_2^t\frac{\partial\boldsymbol{a}}{\partial\mathbf{V}}\biggr]_{1,:}%
=\boldsymbol{u}_2\boldsymbol{h}^t\in\mathbb{R}^{C\times K}$$

In [18]:
print(u2[0], h[0, :], tf.tensordot(u2[0], h[0, :], axes=0))
#gV = u2[0] @ tf.transpose(h[0])
#print(u2[0], tf.transpose(h[0]), gV)

tf.Tensor([-0.2689  0.2689], shape=(2,), dtype=float32) tf.Tensor([0.  0.5], shape=(2,), dtype=float32) tf.Tensor(
[[-0.     -0.1345]
 [ 0.      0.1345]], shape=(2, 2), dtype=float32)


$$\begin{align*}
\boldsymbol{\nabla}_{\mathbf{V}}\mathcal{L}%
&=\biggl[\frac{\partial\mathcal{L}}{\partial\mathbf{V}}\biggr]_{1,:}%
=\boldsymbol{u}_2\boldsymbol{h}^t\in\mathbb{R}^{C\times K}\\%
\boldsymbol{\nabla}_{\boldsymbol{b}_2}\mathcal{L}%
&=\biggl(\frac{\partial\mathcal{L}}{\partial\boldsymbol{b}_2}\biggr)^t%
=\boldsymbol{u}_2\in\mathbb{R}^C\\%
\boldsymbol{u}_1=\boldsymbol{\nabla}_{\boldsymbol{z}}\mathcal{L}%
&=\biggl(\frac{\partial\mathcal{L}}{\partial\boldsymbol{z}}\biggr)^t%
=(\mathbf{V}^t\boldsymbol{u}_2)\odot H(\boldsymbol{z})\in\mathbb{R}^K\\%
\boldsymbol{\nabla}_{\mathbf{W}}\mathcal{L}%
&=\biggl[\frac{\partial\mathcal{L}}{\partial\mathbf{W}}\biggr]_{1,:}%
=\boldsymbol{u}_1\boldsymbol{x}^t\in\mathbb{R}^{K\times D}\\%
\boldsymbol{\nabla}_{\boldsymbol{b}_1}\mathcal{L}%
&=\biggl(\frac{\partial\mathcal{L}}{\partial\boldsymbol{b}_1}\biggr)^t%
=\boldsymbol{u}_1\in\mathbb{R}^K\\%
\boldsymbol{\nabla}_{\boldsymbol{x}}\mathcal{L}%
&=\biggl(\frac{\partial\mathcal{L}}{\partial\boldsymbol{x}}\biggr)^t%
=\mathbf{W}^t\boldsymbol{u}_1\in\mathbb{R}^D%
\end{align*}$$

In [ ]:

z = L1_preact(X); print('z =', str(z).replace('\n',''))
h = L1(X); print('h =', str(h).replace('\n',''))
L2logits = L2_preact(h); print('logits =', str(L2logits).replace('\n','')) # softmax
y_pred = L2(h); print('y_pred =', str(y_pred).replace('\n',''))
eL2 = np.exp(L2logits)
y_pred_alt = np.transpose(eL2.T / eL2.sum(axis=1))
print('y_pred_alt =', str(y_pred_alt).replace('\n','')) # softmax a mano
loss = tf.keras.losses.CategoricalCrossentropy(from_logits=False)
print('loss =', loss(y, y_pred)); 
loss_alt_all = -y * np.log(y_pred) # loss a mano
print('loss_alt_data =', str(loss_alt_all).replace('\n',''))
print('loss_alt =', tf.reduce_sum(loss_alt_all) / 4.) # SUM_OVER_BATCH_SIZE