# XOR: backprop keras para MLP CrossEntropy

In [5]:
import numpy as np; np.set_printoptions(precision=4)
import tensorflow as tf; from tensorflow import keras

In [6]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[1, 0], [0, 1], [0, 1], [1, 0]])
W = tf.constant_initializer([[1, 1], [1, 1]]); tf.transpose(W); b1 = tf.constant_initializer([-1,  .5])
V = tf.constant_initializer([[1, -1], [-1, 1]]); tf.transpose(V); b2 = tf.constant_initializer([ 1, -1])
L1 = keras.layers.Dense(2, activation=tf.nn.relu, input_dim=2, kernel_initializer=W, bias_initializer=b1)
L2 = keras.layers.Dense(2, activation=tf.nn.softmax, kernel_initializer=V, bias_initializer=b2)
M = keras.Sequential([L1, L2])

In [7]:
L1_preact = keras.layers.Dense(2, activation=None, input_dim=2, kernel_initializer=W, bias_initializer=b1)
z = L1_preact(X); print('z =', str(z).replace('\n',''))
h = L1(X); print('h =', str(h).replace('\n',''))
L2_preact = keras.layers.Dense(2, activation=None, kernel_initializer=V, bias_initializer=b2)
a = L2_preact(h); print('a =', str(a).replace('\n','')) # softmax
p = L2(h); print('p =', str(p).replace('\n',''))
L = tf.keras.losses.CategoricalCrossentropy(from_logits=False); print('L =', L(y, p))

z = tf.Tensor([[-1.   0.5] [ 0.   1.5] [ 0.   1.5] [ 1.   2.5]], shape=(4, 2), dtype=float32)
h = tf.Tensor([[0.  0.5] [0.  1.5] [0.  1.5] [1.  2.5]], shape=(4, 2), dtype=float32)
a = tf.Tensor([[ 0.5 -0.5] [-0.5  0.5] [-0.5  0.5] [-0.5  0.5]], shape=(4, 2), dtype=float32)
p = tf.Tensor([[0.7311 0.2689] [0.2689 0.7311] [0.2689 0.7311] [0.2689 0.7311]], shape=(4, 2), dtype=float32)
L = tf.Tensor(0.56326175, shape=(), dtype=float32)


In [8]:
optimizer = tf.optimizers.SGD(learning_rate=0.1)
M.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
M.fit(X, y, epochs=1, verbose=1); print(L1.get_weights(), "\n", L2.get_weights())

1/1 [==============================] - 0s 232ms/step - loss: 0.5633 - accuracy: 0.7500
[array([[1.0366, 0.9769],
       [1.0366, 0.9769]], dtype=float32), array([-0.9634,  0.4769], dtype=float32)] 
 [array([[ 1.0183, -1.0183],
       [-0.9711,  0.9711]], dtype=float32), array([ 1.0116, -1.0116], dtype=float32)]
