# Conexión entre la SVD y la EVD

## Matriz cuadrada real, simétrica y definida positiva

Sea $\mathbf{A}\in\mathbb{R}^{n\times n}$ real, simétrica y definida positiva, con EVD y SVD:
$$\mathbf{A}=\mathbf{E}\mathbf{\Lambda}\mathbf{E}^t%
\qquad\text{y}\qquad%
\mathbf{A}=\mathbf{U}\mathbf{S}\mathbf{V}^t$$

**Valores singulares igual a propios:** $\;\mathbf{S}=\mathbf{\Lambda}$

**Vectores singulares izquierdos y derechos igual a propios (salvo cambios de signo):** $\;\mathbf{U}=\mathbf{V}=\mathbf{E}$

In [1]:
import numpy as np
X = np.array([ [-1, -1], [0, 2], [2, 0], [3, 3] ]).astype(float)
A = np.cov(X.T, bias=True)
L, E = np.linalg.eigh(A)
i = L.argsort()[::-1]; L = L[i]; E = E[:,i]
print("EVD:\n", L, "\n", E, "\n")
U, S, Vt = np.linalg.svd(A)
print("SVD:\n", U, "\n", S, "\n", Vt)

EVD:
 [4. 1.] 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]] 

SVD:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]] 
 [4. 1.] 
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
