## Conexión entre la SVD y la EVD

Si $\mathbf{A}$ es una matriz cuadrada, real, simétrica y definida positiva, se cumple que:
* Los valores singulares son los valores propios
* Los vectores singulares izquierdos y derechos son los vectores propios (salvo cambios de signo):
$$\;\mathbf{A}=\mathbf{U}\mathbf{S}\mathbf{V}^t=\mathbf{U}\mathbf{S}\mathbf{U}^t=\mathbf{U}\mathbf{S}\mathbf{U}^{-1}$$

**Ejemplo:** $\;\mathbf{X}^t=\begin{bmatrix}-1&0&2&3\\-1&2&0&3\end{bmatrix}$

In [1]:
import numpy as np

X = np.array([ [-1, -1], [0, 2], [2, 0], [3, 3] ])
A = np.cov(X.T, bias=True)
L, E = np.linalg.eigh(A)
i = L.argsort()[::-1]; L = L[i]; E = E[:,i]
print("EVD:\n", L, "\n", E, "\n")
U, S, Vt = np.linalg.svd(A)
print("SVD:\n", U, "\n", S, "\n", Vt)

EVD:
 [4. 1.] 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]] 

SVD:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]] 
 [4. 1.] 
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
