# 7.1.1 Notación

## Vectores

**Vector $\boldsymbol{x}\in\mathbb{R}^n$:** $\;$ suponemos que es vector columna
$$\boldsymbol{x}=(x_1, x_2, \dotsc, x_n)^t$$

**Vector de todo unos y todo ceros:** $\quad\boldsymbol{1}\quad\boldsymbol{0}$

**Vector unitario $\boldsymbol{e}_i$** o **one-hot:** $\;$ todo ceros salvo un uno en la posición $i$
$$\boldsymbol{e}_i=(0,\dotsc,0,1,0,\dotsc,0)^t$$

## Matrices

**Matriz $\mathbf{A}\in\mathbb{R}^{m\times n}$:** $\;$ **cuadrada** si $m=n$
$$\mathbf{A}=\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\%
a_{21} & a_{22} & \cdots & a_{2n}\\%
\vdots & \vdots & \ddots & \vdots\\%
a_{m1} & a_{m2} & \cdots & a_{mn}%
\end{bmatrix}$$

**Entrada de la $i$-ésima fila y $j$-ésima columna:** $\;A_{ij}$ o $A_{i,j}$

**Fila $i$-ésima y columna $j$-ésima:** $\;\mathbf{A}_{i,:}$ y $\mathbf{A}_{:,j}$: 


**Matriz vista por filas:** $\;\mathbf{A}=[\mathbf{A}_{1,:};\;\mathbf{A}_{2,:};\;\dotsc;\;\mathbf{A}_{n,:}]$

**Matriz vista por columnas:** $\;\mathbf{A}=[\mathbf{A}_{:,1},\;\mathbf{A}_{:,2},\;\dotsc,\;\mathbf{A}_{:,n}]$

**Transpuesta de $\mathbf{A}\in\mathbb{R}^{m\times n}$:** $\;\mathbf{A}^t\in\mathbb{R}^{n\times m}$ tal que $(\mathbf{A}^t)_{ij}=A_{ji}$, cumple
$$\begin{align*}
(\mathbf{A}^t)^t&=\mathbf{A}\\%
(\mathbf{A}\mathbf{B})^t&=\mathbf{B}^t\mathbf{A}^t\\%
(\mathbf{A}+\mathbf{B})^t&=\mathbf{A}^t+\mathbf{B}^t%
\end{align*}$$

**Matriz simétrica:** $\;$ matriz cuadrada $\mathbf{A}$ tal que $\mathbf{A}=\mathbf{A}^t$; $\;\mathbb{S}^n$ denota todas las matrices simétricas de talla $n$

**Reformato de matriz a vector:** $\;\operatorname{vec}(\mathbf{A})=[\mathbf{A}_{:,1};\;\mathbf{A}_{:,2};\;\cdots;\;\mathbf{A}_{:,n}]\in\mathbf{R}^{mn\times 1}$

**Reformato de vector a matriz:** puede ser por filas (python, C++) o por columnas (julia, octave, R, fortran)

## Tensores

**Tensor:** generalización de matriz a tres o más dimensiones

**Orden** o **rango:** dimensiones (concepto distinto en matrices)

**Ejemplo:** vector 8-dimensional reformatado como matriz y tensor

In [1]:
import numpy as np
a = np.arange(8)
print(a, a.shape)
a2d = a.reshape([2, -1])
print(a2d, a2d.shape)
a3d = a.reshape([2, 2, -1])
print(a3d, a3d.shape)


[0 1 2 3 4 5 6 7] (8,)
[[0 1 2 3]
 [4 5 6 7]] (2, 4)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] (2, 2, 2)
