# Introducción al algebra lineal

## Vectores, matrices y tensores

In [2]:
# %load '7.1.1.notation.py'
import numpy as np
a = np.arange(8)
print(a, a.shape)
a2d = a.reshape([2, -1])
print(a2d, a2d.shape)
a3d = a.reshape([2, 2, -1])
print(a3d, a3d.shape)


[0 1 2 3 4 5 6 7] (8,)
[[0 1 2 3]
 [4 5 6 7]] (2, 4)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] (2, 2, 2)


## Rango de una matriz

In [4]:
# %load '7.1.2.rank.py'
import numpy as np
A = np.eye(4)
print(np.linalg.matrix_rank(A))
A[-1, -1] = 0.
print(np.linalg.matrix_rank(A))
A = np.ones((4,))
print(np.linalg.matrix_rank(A))
A = np.zeros((4,))
print(np.linalg.matrix_rank(A))


4
3
1
0


## Normas L1, L2 y L $\!\infty$ de un vector

In [6]:
# %load '7.1.3.1.vecnorm.py'
import numpy as np
a = np.array([-3, 4])
print(np.linalg.norm(a, 1))
print(np.linalg.norm(a, 2))
print(np.linalg.norm(a, np.inf))


7.0
5.0
4.0


## Norma de Frobenius de una matriz

In [8]:
# %load '7.1.3.2.matnorm.py'
import numpy as np
A = np.array([[-2, -2], [2, 2]])
print(np.linalg.norm(A, 'fro'))


4.0


## Propiedades de una matriz

In [10]:
# %load '7.1.4.matprops.py'
import numpy as np
A = np.array([[2, 1], [1, 2]])
print(np.trace(A))
print(round(np.linalg.det(A)))
print(np.linalg.matrix_rank(A))
print(round(np.linalg.cond(A)))


4
3
2
3
